"""add reason to database_requests

Revision ID: 3725c8112fd8
Revises: 92dcd2f11538
Create Date: 2026-04-15 22:25:35.836450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3725c8112fd8'
down_revision = '92dcd2f11538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
