"""add database lifecycle schema

Revision ID: 92dcd2f11538
Revises: 972783a8efef
Create Date: 2026-04-15 13:50:06.484924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dcd2f11538'
down_revision = '972783a8efef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['pg_instances.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'name', name='uq_asset_instance_name')
    )
    with op.batch_alter_table('database_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_assets_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_assets_team_id'), ['team_id'], unique=False)

    op.create_table('database_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('database_name', sa.String(length=63), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('database_asset_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('operation_output', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['database_asset_id'], ['database_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['pg_instances.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_requests_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_requests_team_id'), ['team_id'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('database_asset_id', sa.Integer(), nullable=True),
    sa.Column('database_request_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['database_asset_id'], ['database_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['database_request_id'], ['database_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_database_asset_id'), ['database_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_database_request_id'), ['database_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_status'), ['status'], unique=False)

    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'create_db_script', sa.String(length=500), nullable=False,
            server_default='/home/postgres/beheer/scripts/create_database.sh'
        ))
        batch_op.add_column(sa.Column(
            'delete_db_script', sa.String(length=500), nullable=False,
            server_default='/home/postgres/beheer/scripts/delete_database.sh'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('delete_db_script')
        batch_op.drop_column('create_db_script')

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_status'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_database_request_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_database_asset_id'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_requests_team_id'))
        batch_op.drop_index(batch_op.f('ix_database_requests_status'))
        batch_op.drop_index(batch_op.f('ix_database_requests_request_type'))
        batch_op.drop_index(batch_op.f('ix_database_requests_instance_id'))

    op.drop_table('database_requests')
    with op.batch_alter_table('database_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_assets_team_id'))
        batch_op.drop_index(batch_op.f('ix_database_assets_status'))
        batch_op.drop_index(batch_op.f('ix_database_assets_instance_id'))

    op.drop_table('database_assets')
    # ### end Alembic commands ###
