"""add cluster schema

Revision ID: 972783a8efef
Revises: af7138c98654
Create Date: 2026-04-15 12:32:39.650640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972783a8efef'
down_revision = 'af7138c98654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('load_balancer', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ssh_user', sa.String(length=100), nullable=False),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_status'), ['status'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'hostname', name='uq_node_cluster_hostname')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('pg_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=120), nullable=False),
    sa.Column('pgdata_dir', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'hostname', 'port', name='uq_instance_cluster_host_port')
    )
    with op.batch_alter_table('pg_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pg_instances_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('team_cluster_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'cluster_id', name='uq_team_cluster')
    )
    with op.batch_alter_table('team_cluster_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_cluster_permissions_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_cluster_permissions_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_cluster_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_cluster_permissions_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_cluster_permissions_cluster_id'))

    op.drop_table('team_cluster_permissions')
    with op.batch_alter_table('pg_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pg_instances_cluster_id'))

    op.drop_table('pg_instances')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_cluster_id'))

    op.drop_table('nodes')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_status'))

    op.drop_table('clusters')
    # ### end Alembic commands ###
